# Generated by Django 5.1.2 on 2026-02-18 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('formato', models.CharField(choices=[('vinilo', 'Vinilo'), ('CD', 'CD'), ('Cassette', 'Cassette')], max_length=20)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('discografica', models.CharField(max_length=300)),
                ('num_pistas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('genero', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('usada', 'Usada'), ('deteriorada', 'Deteriorada'), ('retirar', 'A retirar')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('formato', models.CharField(choices=[('VHS', 'VHS'), ('CD', 'CD'), ('DVD', 'DVD')], max_length=4)),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('duracion_minutos', models.FloatField()),
                ('genero', models.CharField(max_length=300)),
                ('sinopsis', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Autor_Disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Artista', 'Artista'), ('Productor', 'Productor'), ('Compositor', 'Compositor')], verbose_name=100)),
                ('autor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.autor')),
                ('disco_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.disco')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('tipo_publicacion', models.CharField(choices=[('libro', 'Libro'), ('articulo', 'Artículo')], max_length=10)),
                ('año_publicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('editorial', models.CharField(max_length=200)),
                ('autores', models.ManyToManyField(related_name='publicaciones', to='socios.autor')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Autor_Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Director', 'Director'), ('Guionista', 'Guionista'), ('Guionista', 'Guionista')], verbose_name=100)),
                ('autor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.autor')),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socios.video')),
            ],
        ),
    ]
